name: nest_asyncio

on:
  push:
    branches:
      - master
  pull_request:

env:
  FORCE_COLOR: 1

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install uv
          uv tool install mypy
          uv tool install ruff

      - name: Ruff lint
        run: ruff check nest_asyncio.py

      - name: MyPy type check
        run: mypy nest_asyncio.py


  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Testsuite
        run: |
          pip install .
          python tests/nest_test.py
